<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

		<!-- Habilita suporte completo a MVC (Views, Controllers, TagHelpers) -->
		<AddRazorSupportForMvc>true</AddRazorSupportForMvc>
	</PropertyGroup>

	<ItemGroup>
		<!-- Referência ao ASP.NET Core completo -->
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Core\Core.csproj" />
	  <ProjectReference Include="..\Domain\Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="temp-build\**\*.cs" />
	  <Content Remove="temp-build\**\*" />
	  <EmbeddedResource Remove="temp-build\**\*" />
	  <None Remove="temp-build\**\*" />
	</ItemGroup>

</Project>
